### ISSUE TITLE
Github action "Push Docker Image"doesn't work with Uppercase repository name

### ISSUE THREAD

**Issue by Lp-Francois** [codefresh-contrib/gitops-cert-level-2-examples#62]
Hello!

During the Argo Image Updater exercise, it requires to use `docker push` step, but it fails with uppercase repository name (like mine 😅)

Seems to be related to this issue: https://github.com/docker/build-push-action/issues/37

How about using another "unique identifier" than the repository name? Or lowercase the name? (https://github.com/orgs/community/discussions/25768)

Best,

**Comment by Lp-Francois** [comment]
After giving a try to the GitHub action: ASzc/change-string-case-action@v2, the workflow worked ✅

**Example commit**: https://github.com/Lp-Francois/gitops-cert-level-2-examples/commit/1121fb39921507736c8161e4e7cf635ea5221c6f
**Example workflow**: https://github.com/Lp-Francois/gitops-cert-level-2-examples/actions/runs/3503615687

Let me know if I should push a PR

**Comment by todaywasawesome** [comment]
@Lp-Francois I think that would make a great PR. I don't know if there are any other possible values in a repo name that would be invalid for an image, it would be nice to cover those but I'd settle for having this PR today :)

**Comment by kostis-codefresh** [comment]
Fixed as part of https://github.com/codefresh-contrib/gitops-cert-level-2-examples/pull/66

Thanks!
